export const seedAuthors = [
  {
    _id: "author-maya-ito",
    _type: "author",
    name: "Maya Ito",
    bio: "Maya writes about the rituals of walking, waiting, and working with compact cameras after midnight.",
    instagram: "@maya.afterhours",
  },
  {
    _id: "author-jonah-vale",
    _type: "author",
    name: "Jonah Vale",
    bio: "Jonah covers bags, books, and the small design decisions that shape the lived experience of carrying a camera.",
    instagram: "@jonahvale",
  },
];

export const seedIssue = {
  _id: "issue-2026-04",
  _type: "issue",
  title: "After Hours, Before Dawn",
  issueNumber: "01",
  month: "April",
  year: 2026,
};

export const seedProducts = [
  {
    _id: "product-ricoh-griiix",
    _type: "product",
    name: "Ricoh GR IIIx Urban Shadow",
    slug: { _type: "slug", current: "ricoh-griiix-urban-shadow" },
    brand: "Ricoh",
    price: 1099,
    comparePrice: 1199,
    category: "camera",
    inStock: true,
    stripePriceId: "price_demo_gr3x",
    tags: ["compact", "street", "40mm equivalent"],
    specs: [
      { _key: "sensor", key: "Sensor", value: "24.2MP APS-C CMOS" },
      { _key: "lens", key: "Lens", value: "40mm equiv f/2.8" },
    ],
  },
  {
    _id: "product-bellroy-sling",
    _type: "product",
    name: "Bellroy Venture Sling 6L",
    slug: { _type: "slug", current: "bellroy-venture-sling-6l" },
    brand: "Bellroy",
    price: 139,
    category: "bag",
    inStock: true,
    stripePriceId: "price_demo_sling",
    tags: ["bag", "weatherproof", "daily carry"],
  },
  {
    _id: "product-godox-lux-jr",
    _type: "product",
    name: "Godox Lux Junior Flash",
    slug: { _type: "slug", current: "godox-lux-junior-flash" },
    brand: "Godox",
    price: 79,
    category: "flash",
    inStock: true,
    stripePriceId: "price_demo_flash",
    tags: ["flash", "portable", "retro"],
  },
  {
    _id: "product-cinebloom",
    _type: "product",
    name: "CineBloom 10% Filter",
    slug: { _type: "slug", current: "cinebloom-10-filter" },
    brand: "Moment",
    price: 69,
    category: "filter",
    inStock: true,
    stripePriceId: "price_demo_filter",
    tags: ["diffusion", "night", "bloom"],
  },
  {
    _id: "product-camera-strap",
    _type: "product",
    name: "Leather Wrist Strap, Smoke Tan",
    slug: { _type: "slug", current: "leather-wrist-strap-smoke-tan" },
    brand: "Artefact",
    price: 54,
    category: "accessory",
    inStock: true,
    stripePriceId: "price_demo_strap",
    tags: ["strap", "leather", "minimal"],
  },
  {
    _id: "product-portra-400",
    _type: "product",
    name: "Kodak Portra 400",
    slug: { _type: "slug", current: "kodak-portra-400" },
    brand: "Kodak",
    price: 18,
    category: "film",
    inStock: true,
    stripePriceId: "price_demo_portra",
    tags: ["film", "35mm", "color negative"],
  },
  {
    _id: "product-bag-insert",
    _type: "product",
    name: "Modular Insert, Coal Felt",
    slug: { _type: "slug", current: "modular-insert-coal-felt" },
    brand: "Wotancraft",
    price: 49,
    category: "bag accessory",
    inStock: true,
    stripePriceId: "price_demo_insert",
    tags: ["organization", "insert", "felt"],
  },
  {
    _id: "product-hoya-hood",
    _type: "product",
    name: "Metal Ventilated Lens Hood",
    slug: { _type: "slug", current: "metal-ventilated-lens-hood" },
    brand: "Squarehood",
    price: 85,
    category: "accessory",
    inStock: true,
    stripePriceId: "price_demo_hood",
    tags: ["lens hood", "metal", "street"],
  },
  {
    _id: "product-peak-clip",
    _type: "product",
    name: "Capture Clip V3",
    slug: { _type: "slug", current: "capture-clip-v3" },
    brand: "Peak Design",
    price: 74,
    category: "accessory",
    inStock: true,
    stripePriceId: "price_demo_clip",
    tags: ["clip", "carry", "hands-free"],
  },
  {
    _id: "product-contact-book",
    _type: "product",
    name: "Contact Sheet Notebook",
    slug: { _type: "slug", current: "contact-sheet-notebook" },
    brand: "LENS & LORE Editions",
    price: 32,
    category: "print",
    inStock: true,
    stripePriceId: "price_demo_notebook",
    tags: ["notebook", "archive", "edition"],
  },
];

export const seedArticles = [
  {
    _id: "article-neon-after-rain",
    _type: "article",
    title: "Neon After Rain: The Cameras That Love Wet Pavement",
    slug: { _type: "slug", current: "neon-after-rain" },
    issue: { _type: "reference", _ref: "issue-2026-04" },
    author: { _type: "reference", _ref: "author-maya-ito" },
    category: "gear",
    body: [
      {
        _key: "block-intro",
        _type: "block",
        style: "normal",
        children: [
          {
            _key: "span-1",
            _type: "span",
            text: "At 1:13 a.m., puddles become mirrors and every passing taxi turns the street into a temporary light installation.",
            marks: [],
          },
        ],
      },
      {
        _key: "embed-1",
        _type: "productEmbed",
        heading: "Used In This Story",
        note: "The GR IIIx keeps the frame honest while the diffusion filter takes the edge off hard signage.",
        product: { _type: "reference", _ref: "product-ricoh-griiix" },
      },
    ],
    featuredProducts: [
      {
        _key: "featured-1",
        product: { _type: "reference", _ref: "product-ricoh-griiix" },
        contextNote: "The compact body disappears until the moment a reflection opens up.",
      },
      {
        _key: "featured-2",
        product: { _type: "reference", _ref: "product-cinebloom" },
        contextNote: "A touch of bloom turns hard storefront light into atmosphere.",
      },
    ],
    seoMeta: {
      title: "Neon After Rain | LENS & LORE",
      description: "An editorial on compact cameras, rain-soaked sidewalks, and lenses built for midnight color.",
    },
  },
  {
    _id: "article-invisible-shoulder-bag",
    _type: "article",
    title: "What Makes A Shoulder Bag Feel Invisible At Hour Six",
    slug: { _type: "slug", current: "invisible-shoulder-bag" },
    issue: { _type: "reference", _ref: "issue-2026-04" },
    author: { _type: "reference", _ref: "author-jonah-vale" },
    category: "culture",
    body: [],
    featuredProducts: [
      {
        _key: "featured-3",
        product: { _type: "reference", _ref: "product-bellroy-sling" },
        contextNote: "Quiet hardware, quick access, and enough give to disappear into the shoulder.",
      },
    ],
  },
  {
    _id: "article-pocket-flash-revival",
    _type: "article",
    title: "The Pocket Flash Revival Happening Between Bars And Bodegas",
    slug: { _type: "slug", current: "pocket-flash-revival" },
    issue: { _type: "reference", _ref: "issue-2026-04" },
    author: { _type: "reference", _ref: "author-maya-ito" },
    category: "photography",
    body: [],
    featuredProducts: [
      {
        _key: "featured-4",
        product: { _type: "reference", _ref: "product-godox-lux-jr" },
        contextNote: "Small enough to keep in the pocket, punchy enough to shift the mood.",
      },
    ],
  },
];
